1) From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [11]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df = df.loc[0:93:20, "Manufacturer" : "Type"]
display(df)

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Manufacturer').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Model').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Type').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Model'].value_counts()
    for x_label, grp in df.groupby('Manufacturer')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Manufacturer')
_ = plt.ylabel('Model')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Type'].value_counts()
    for x_label, grp in df.groupby('Model')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Model')
_ = plt.ylabel('Type')

2) Replace missing values in Min.Price and Max.Price columns with their respective mean (check documentation).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')


In [25]:
import pandas as pd


df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
null_count = df['Min.Price'].isnull().sum()
print("Number of null values in 'Min.Price' column:", null_count)

min_price_mean = df['Min.Price'].mean()
df['Min.Price'] = df['Min.Price'].apply(lambda x: min_price_mean if pd.isnull(x) else x)


max_price_mean = df['Max.Price'].mean()
df['Max.Price'] = df['Max.Price'].apply(lambda x: max_price_mean if pd.isnull(x) else x)

print(df)
null_count = df['Min.Price'].isnull().sum()
print("Number of null values in 'Min.Price' column:", null_count)




Number of null values in 'Min.Price' column: 7
   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags Driv

3) How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rows_sum_gt_100 = df[df.sum(axis=1) > 100]
print("Rows with row sum > 100:")
print(rows_sum_gt_100)




Rows with row sum > 100:
     0   1   2   3
0   23  35  14  36
1   10  34  25  34
2   32  28  24  19
3   30  21  39  36
4   38  20  28  34
5   28  17  34  29
6   38  29  18  26
8   25  38  18  37
9   30  31  35  21
10  37  38  26  19
14  29  22  31  33


4)Create a 4x4 NumPy array filled with random integers between 1 and 100. Then, reshape this array into two separate 2D arrays, where one represents the rows and the other represents the columns. Write a function, preferably using a lambda function, to calculate the sum of each row and each column separately, and return the results as two separate NumPy arrays

In [4]:
import numpy as np

arr = np.random.randint(1, 101, (4, 4))
print(arr)

rows_array = arr.reshape(2, 8)
print(rows_array)
columns_array = arr.T.reshape(2, 8)
print(columns_array)

sum_row_column = lambda x: np.sum(x, axis=1)

sum_of_rows = sum_row_column(rows_array)
sum_of_columns = sum_row_column(columns_array)

print("Sum of each row separately:", sum_of_rows)
print("Sum of each column separately:", sum_of_columns)


[[84  4 37 72]
 [63 63 11 45]
 [37 71 10 46]
 [37 23 54 21]]
[[84  4 37 72 63 63 11 45]
 [37 71 10 46 37 23 54 21]]
[[84 63 37 37  4 63 71 23]
 [37 11 10 54 72 45 46 21]]
Sum of each row separately: [379 299]
Sum of each column separately: [382 296]
